#!/usr/bin/env node
/**
 * Generates src/features/contact/MapArt.tsx: the decorative Lahore map SVG of the Contact page
 * (reference `svg.ct-map__svg`), converted from the reference markup to JSX so that not a single
 * path is typed by hand. Only the attribute names change (class to className, kebab-case to camelCase).
 *
 * Usage (from frontend/): node scripts/gen-map-art.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REFERENCE = resolve(HERE, '../../reference-design/faisalhanif-redesign.html');
const OUT = resolve(HERE, '../src/features/contact/MapArt.tsx');

const source = readFileSync(REFERENCE, 'utf8');
const start = source.indexOf('<svg class="ct-map__svg"');
if (start < 0) throw new Error('ct-map__svg not found in the reference');
const end = source.indexOf('</svg>', start) + '</svg>'.length;
let svg = source.slice(start, end);

const camel = (name) => name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());
svg = svg.replace(/(\s)([a-zA-Z][\w:-]*)=/g, (all, sp, name) => {
  if (name === 'class') return `${sp}className=`;
  if (name.startsWith('data-') || name.startsWith('aria-')) return all;
  return `${sp}${camel(name)}=`;
});
// Keep the first tag's `aria-hidden`/`focusable` as written; the map is decorative.
const body = svg
  .split('\n')
  .map((line) => (line.trim() ? '    ' + line.replace(/^\s+/, (m) => m) : line))
  .join('\n');

const file = `/**
 * GENERATED by scripts/gen-map-art.mjs from reference-design/faisalhanif-redesign.html
 * (svg.ct-map__svg, reference L4416-4478). Do not edit by hand: run the script again.
 *
 * The decorative map of Lahore for the Contact page: grid, distance rings, the river Ravi, roads,
 * nearby towns, the beam and the pulsing pin. Static markup; the CSS animates it.
 */
export function MapArt() {
  return (
${body.replace(/^/, '    ').replace(/^ {4} {4}/, '    ')}
  );
}
`;
writeFileSync(OUT, file);
console.log('wrote', OUT, file.length, 'bytes');
